# Generated by Django 3.0 on 2019-12-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('windows', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
