# Generated by Django 3.0.1 on 2020-01-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'industry',
                'verbose_name_plural': 'industry',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(default=None, max_length=255, null=True)),
                ('us_state', models.CharField(default=None, max_length=255, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('company_website', models.CharField(default=None, max_length=255, null=True)),
                ('company_address', models.CharField(default=None, max_length=255, null=True)),
                ('nature', models.CharField(default=None, max_length=255, null=True)),
                ('year_established', models.CharField(default=None, max_length=255, null=True)),
                ('activities', models.CharField(default=None, max_length=255, null=True)),
                ('state', models.CharField(default=None, max_length=255, null=True)),
                ('zip', models.CharField(default=None, max_length=255, null=True)),
                ('activities_num', models.CharField(default=None, max_length=255, null=True)),
                ('naics_num', models.CharField(default=None, max_length=255, null=True)),
                ('final_industry_code', models.CharField(default=None, max_length=255, null=True)),
                ('employee_band_company', models.CharField(default=None, max_length=255, null=True)),
                ('kompass_id', models.CharField(default=None, max_length=255, null=True)),
                ('employee_band_at_address', models.CharField(default=None, max_length=255, null=True)),
                ('Latitude', models.CharField(default=None, max_length=255, null=True)),
                ('Longitude', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisation',
            },
        ),
    ]
