# Generated by Django 3.0.1 on 2020-01-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200107_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSScore',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('naics_code', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(max_length=255, unique=True)),
                ('band', models.CharField(max_length=255, unique=True)),
                ('score', models.CharField(max_length=255, unique=True)),
                ('severity', models.CharField(max_length=255, unique=True)),
                ('frequency', models.CharField(max_length=255, unique=True)),
                ('indicator', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cs_score',
                'verbose_name_plural': 'cs_scores',
            },
        ),
    ]
