# Generated by Django 3.0.1 on 2020-01-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_csscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetdScore',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('naics_code', models.CharField(max_length=255, unique=True)),
                ('industry_title', models.CharField(max_length=255, unique=True)),
                ('netd_score', models.CharField(max_length=255, unique=True)),
                ('indicator', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'netd_score',
                'verbose_name_plural': 'netd_scores',
            },
        ),
        migrations.CreateModel(
            name='PonemonScore',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('naics_code', models.CharField(max_length=255, unique=True)),
                ('industry_title', models.CharField(max_length=255, unique=True)),
                ('ponemon_score', models.CharField(max_length=255, unique=True)),
                ('indicator', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ponemon_score',
                'verbose_name_plural': 'ponemon_scores',
            },
        ),
    ]
