# Generated by Django 3.0.1 on 2020-01-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_netdscore_ponemonscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponemonscore',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
