# Generated by Django 3.0.1 on 2020-01-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200107_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponemonscore',
            name='indicator',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ponemonscore',
            name='naics_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ponemonscore',
            name='ponemon_score',
            field=models.CharField(max_length=255),
        ),
    ]
