# Generated by Django 3.0.1 on 2020-01-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200107_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponemonscore',
            name='industry_title',
            field=models.CharField(max_length=255),
        ),
    ]
