# Generated by Django 3.0.1 on 2020-01-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200107_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csscore',
            name='band',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='csscore',
            name='frequency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='csscore',
            name='indicator',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='csscore',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='csscore',
            name='naics_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='csscore',
            name='score',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='csscore',
            name='severity',
            field=models.CharField(max_length=255),
        ),
    ]
