# Generated by Django 3.0.1 on 2020-01-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200107_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csscore',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='netdscore',
            name='indicator',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='netdscore',
            name='industry_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='netdscore',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='netdscore',
            name='naics_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='netdscore',
            name='netd_score',
            field=models.CharField(max_length=255),
        ),
    ]
