# Generated by Django 3.0.1 on 2020-01-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200108_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='k_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
