# Generated by Django 3.0.1 on 2020-01-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200108_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationCounty',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('county_name', models.CharField(default=True, max_length=255, null=True)),
                ('orgs_count', models.IntegerField(default=True, max_length=255, null=True)),
                ('orgs_score', models.CharField(default=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'organisation_county',
                'verbose_name_plural': 'organisation_counties',
            },
        ),
    ]
