# Generated by Django 3.0.1 on 2020-01-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_organisationcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcity',
            name='orgs_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
