# Generated by Django 3.0.1 on 2020-01-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200108_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationZipcode',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('zipcode', models.CharField(default=True, max_length=255, null=True)),
                ('orgs_count', models.IntegerField(default=0, null=True)),
                ('orgs_score', models.CharField(default=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'organisation_zipcode',
                'verbose_name_plural': 'organisation_zipcodes',
            },
        ),
    ]
