# Generated by Django 3.0.1 on 2020-01-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200108_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
